# wrangler.toml
name = 'teutomotoren-page'
compatibility_date = "2026-05-23"
pages_build_output_dir = "."

[[r2_buckets]]
binding = "CONTACT_UPLOADS"
bucket_name = "teutomotoren"
preview_bucket_name = "teutomotoren"
